name: flutter_boilerplate
description: A simple boilerplate project
version: 1.0.0+1
publish_to: none

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_riverpod: ^2.3.0
  riverpod_annotation: 2.0.0
  dio: ^5.0.1
  pretty_dio_logger: ^1.3.1
  flutter_secure_storage: 7.0.1
  shared_preferences: ^2.0.15
  google_fonts: ^4.0.1
  lottie: ^2.2.0
  connectivity_plus: ^3.0.2
  flutter_dotenv: ^5.0.2
  go_router: ^6.0.3
  easy_localization: 3.0.2-dev.5


dev_dependencies:
  #flutter_test:
    #sdk: flutter
  json_serializable:
  go_router_builder: any
  build_runner: any
  build_verify: any
  flutter_gen_runner:
  freezed: ^2.2.1
  riverpod_generator: 2.0.0
  import_sorter: ^4.6.0
  very_good_analysis: 4.0.0+1

## Install derry from https://pub.dev/packages/derry and run derry build, derry watch, derry gen
scripts: derry.yaml

# https://pub.dev/packages/flutter_gen, after new assets run derry gen
flutter_gen:
  output: lib/gen/ # Optional (default: lib/gen/)

  #  integrations:
  #    flutter_svg: true
  #    flare_flutter: true

  assets:
    enabled: true
  fonts:
    enabled: true
  colors:
    enabled: true
    inputs:
      - assets/color/colors.xml
import_sorter:
  comments: false # Optional, defaults to true
  ignored_files: # Optional, defaults to []
    - \/lib\/*
flutter:
  uses-material-design: true
  generate: true
  assets:
    - assets/lang/en.json
    - assets/env/.env.production
    - assets/env/.env.staging
    - assets/env/.env.development
    - assets/env/
    - assets/
    #- assets/image/
